version: '2'
services:
  rest:
    build:
      context: ..
      dockerfile: "docker/Dockerfile_rest"
    image: sj/rest
    ports:
     - "8080:8080"
    volumes:
     - /tmp/sj-rest-log:/var/log/rest
    depends_on:
     - mongo
    links:
     - mongo
    environment:
      - MONGO_HOST=mongo
  mongo:
    image: mongo
    network_mode: "host"